import Link from "next/link";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-[#050505] text-white">
            <div className="max-w-4xl mx-auto px-6 py-24">
                <Link href="/" className="text-sm text-indigo-400 hover:text-indigo-300 mb-8 inline-block">
                    &larr; Back to Home
                </Link>

                <h1 className="text-3xl font-semibold tracking-tight mb-2">Terms of Service</h1>
                <p className="text-xs text-neutral-500 mb-12">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

                <div className="space-y-10 text-sm text-neutral-300 leading-relaxed">

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">1. Agreement to Terms</h2>
                        <p>These Terms of Service (&quot;Terms&quot;) constitute a legally binding agreement made between you, whether personally or on behalf of an entity (&quot;You&quot;) and NextCall Technologies (&quot;NextCall,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), concerning your access to and use of the NextCall AI Receptionist platform and associated services (the &quot;Service&quot;). By accessing or using the Service, you agree that you have read, understood, and agreed to be bound by these Terms. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS, DO NOT ACCESS OR USE THE SERVICE.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">2. Definitions</h2>
                        <ul className="list-disc list-inside space-y-2 mt-3">
                            <li><strong>&quot;Customer Data&quot;</strong> means all data, text, and information submitted by you to the Service, including your Knowledge Base and business profile.</li>
                            <li><strong>&quot;Call Data&quot;</strong> means audio recordings, transcripts, metadata, and AI-generated outputs derived from phone calls processed through the Service.</li>
                            <li><strong>&quot;AI Output&quot;</strong> means the text, summaries, sentiment analyses, and automated responses generated by the artificial intelligence systems powering the Service.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">3. Account Registration & Eligibility</h2>
                        <p>You must create an account to use the Service. You represent and warrant that you are at least <strong>18 years of age</strong> (or the age of legal majority in your jurisdiction) and have the legal capacity to enter into these Terms. If you are using the Service on behalf of a business entity, you represent that you have the authority to bind that entity to these Terms. You are responsible for maintaining the confidentiality of your account credentials (managed via Clerk) and for all activities that occur under your account.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">4. Subscriptions & Billing</h2>
                        <ul className="list-disc list-inside space-y-2 mt-3">
                            <li><strong>Subscription Plans:</strong> The Service is offered on a recurring subscription basis (e.g., Standard, Premium). Subscriptions automatically renew at the end of each billing cycle unless cancelled prior to the renewal date.</li>
                            <li><strong>Payment Processing:</strong> Payments are processed securely via <strong>Paddle</strong> (our Merchant of Record) or other authorized payment providers. You agree to pay all applicable fees and taxes.</li>
                            <li><strong>Overages:</strong> If your usage exceeds the minute limits of your plan, standard overage rates apply, or the Service may be temporarily paused depending on your plan tier.</li>
                            <li><strong>Failed Payments:</strong> If a payment fails, we reserve the right to suspend your access to the Service until the outstanding balance is paid.</li>
                            <li><strong>Price Changes:</strong> We may modify our pricing upon reasonable advance notice to you.</li>
                            <li><strong>Refunds:</strong> Subscription fees are non-refundable, except as expressly set forth in Section 5 (Refund Policy) or required by applicable law.</li>
                        </ul>
                    </section>

                    <section className="border border-white/[0.06] rounded-2xl p-6 bg-white/[0.02]">
                        <h2 className="text-lg font-medium text-white mb-3">5. Refund Policy</h2>
                        <ul className="list-disc list-inside space-y-3 mt-3">
                            <li><strong>Subscription Billing:</strong> NextCall subscriptions are billed in advance on a recurring monthly basis through Paddle. By subscribing, you authorize us to charge your designated payment method for all applicable fees.</li>
                            <li><strong>Cancellation:</strong> You may cancel your subscription at any time. Upon cancellation, your subscription remains active until the end of the current billing cycle. No further charges will be made. We do not issue automatic refunds for the unused portion of a billing cycle after a cancellation, unless explicitly required by law.</li>
                            <li><strong>Refund Eligibility:</strong> If you are unsatisfied with the Service, you may request a refund within <strong>7 days</strong> of your initial subscription purchase. Requests must be sent to our support team at <strong>support@getnextcall.com</strong>. Refunds are evaluated at our sole discretion based on account usage and adherence to these Terms. Approved refunds will be credited back to your original payment method. Please allow 5-10 business days for processing.</li>
                            <li><strong>Overages & Metered Usage:</strong> NextCall incurs real-time costs from third-party providers (Twilio, OpenAI, Retell AI). Any charges for usage that exceeds your plan’s minute limits (Overages) are strictly non-refundable once incurred.</li>
                            <li><strong>Account Termination:</strong> We reserve the right to suspend or terminate your account without a refund if you are found to be violating these Terms, engaging in fraudulent activity, or abusing the telephony infrastructure.</li>
                            <li><strong>Data Deletion:</strong> If you cancel your subscription, your data is retained for 30 days before permanent deletion. No refunds are provided for data retention or deletion processes.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">6. Acceptable Use</h2>
                        <p>You agree not to use the Service for any unlawful purpose or in any way that could damage, disable, or impair the Service. You must comply with all applicable telecommunications, privacy, recording, and consumer protection laws, including the Telephone Consumer Protection Act (TCPA).</p>
                    </section>

                    <section className="border border-white/[0.06] rounded-2xl p-6 bg-white/[0.02]">
                        <h2 className="text-lg font-medium text-white mb-3">7. Call Recording, AI Processing & Legal Compliance</h2>
                        <p>You acknowledge that calls handled through the Service may be recorded, transcribed, analyzed, and processed by AI systems (utilizing Retell AI and OpenAI).</p>
                        <p className="mt-3 font-semibold text-white">Caller Consent &amp; Disclosure: You are solely responsible for providing any legally required notices and obtaining any required consent (including two-party consent) from callers before recording or AI-processing communications. You must disclose to callers that they are interacting with an AI and that calls may be recorded.</p>
                        <p className="mt-3">NextCall assumes no liability for your failure to comply with federal, state, or local call recording and disclosure laws.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">8. Customer Data & Privacy</h2>
                        <p>You retain all right, title, and interest in and to your Customer Data. By submitting Customer Data, you grant NextCall a limited, non-exclusive license to host, process, transmit, and analyze the data solely for the purpose of providing and improving the Service. Your data is stored securely via DataStax AstraDB. We comply with the General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA) to the extent they apply to your use of the Service. Enterprise customers requiring a Data Processing Agreement (DPA) may request one at support@getnextcall.com. For full details, see our Privacy Policy.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">9. Intellectual Property</h2>
                        <p>NextCall retains all rights, title, and interest in the Service, software, source code, algorithms, and trademarks. Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable right to use the Service during your active subscription term.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">10. Service Availability & Force Majeure</h2>
                        <p>We strive to maintain high availability but do not guarantee uninterrupted or error-free operation. Scheduled maintenance, third-party provider outages (e.g., Twilio, OpenAI), and events beyond our control may affect availability. We reserve the right to modify, suspend, or discontinue any part of the Service with reasonable notice.</p>
                        <p className="mt-3"><strong>Force Majeure:</strong> We shall not be liable for any delay or failure in performance resulting from acts beyond our reasonable control, including but not limited to acts of God, natural disasters, war, terrorism, strikes, labor disputes, internet outages, or failures of third-party telecommunications networks.</p>
                    </section>

                    <section className="border border-white/[0.06] rounded-2xl p-6 bg-white/[0.02]">
                        <h2 className="text-lg font-medium text-white mb-3">11. AI Output Disclaimer</h2>
                        <p>The Service uses artificial intelligence to route calls, generate transcripts, summaries, and automated responses. AI Output may be inaccurate, incomplete, delayed, or unsuitable for a particular purpose.</p>
                        <p className="mt-3 font-semibold text-white">You are responsible for reviewing and verifying all AI Output before relying on it. The Service is not intended to replace emergency services, professional dispatch, legal advice, medical advice, or human judgment in high-stakes situations.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">12. Warranty Disclaimer</h2>
                        <p>THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS, WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. WE DISCLAIM ALL WARRANTIES, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">13. Limitation of Liability</h2>
                        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
                        <ul className="list-disc list-inside space-y-2 mt-3">
                            <li>WE WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST BUSINESS, LOST DATA, OR BUSINESS INTERRUPTION.</li>
                            <li>OUR TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THE SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID TO NEXTCALL DURING THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">14. Indemnification</h2>
                        <p>You agree to defend, indemnify, and hold harmless NextCall and its officers, directors, and employees from and against any claims, damages, losses, and expenses (including reasonable attorneys&apos; fees) arising out of or in connection with your use of the Service, your violation of these Terms, your violation of applicable law, or your failure to obtain caller consent.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">15. Termination</h2>
                        <p>You may cancel your subscription at any time. Upon cancellation, your account will enter a 30-day grace period. After 30 days, your account and associated Customer Data will be permanently deleted. We reserve the right to suspend or terminate your account immediately in the event of a material breach of these Terms.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">16. Dispute Resolution, Arbitration & Class Action Waiver</h2>
                        <p className="mb-3"><strong>Binding Arbitration:</strong> Any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be finally resolved by binding arbitration administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules. Either party may bring claims in small claims court if eligible. Any claim must be initiated within one (1) year of the event giving rise to it. You may opt out of this arbitration agreement within 30 days of first accepting these Terms by emailing support@getnextcall.com.</p>
                        <p className="mb-3"><strong>Class Action Waiver:</strong> You and NextCall agree that each may bring claims against the other only in your or its individual capacity, and not as a plaintiff or class member in any purported class, consolidated, or representative proceeding.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">17. Governing Law</h2>
                        <p>These Terms are governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict-of-law principles. The courts located in Delaware shall have exclusive jurisdiction over any appeals from an arbitration award or any claims not subject to arbitration.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">18. Changes to Terms</h2>
                        <p>We reserve the right to update or modify these Terms at any time. We will provide notice of material changes by posting the updated Terms on our website, updating the &quot;Last updated&quot; date, and, where practical, sending an email or in-app notification. Your continued use of the Service after changes are posted constitutes your acceptance of the updated Terms.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">19. General Provisions</h2>
                        <ul className="list-disc list-inside space-y-2 mt-3">
                            <li><strong>Severability:</strong> If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions will remain in full force and effect.</li>
                            <li><strong>Entire Agreement:</strong> These Terms, together with the Privacy Policy, constitute the entire agreement between you and NextCall regarding the Service and supersede all prior agreements.</li>
                            <li><strong>Waiver:</strong> The failure of NextCall to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.</li>
                            <li><strong>Assignment:</strong> You may not assign or transfer these Terms without our prior written consent. We may assign or transfer these Terms, in whole or in part, without restriction in the event of a merger, acquisition, or sale of all or a portion of our assets.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-lg font-medium text-white mb-3">20. Contact & Legal Notices</h2>
                        <p>If you have any questions, notices, or legal requests regarding these Terms or the Service, please contact us at:</p>
                        <p className="mt-3">
                            NextCall Technologies<br />
                            1201 Orange St, Suite 600, Wilmington, DE 19801<br />
                            Email: <a href="mailto:support@getnextcall.com" className="text-indigo-400 hover:text-indigo-300">support@getnextcall.com</a>
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}